name: Vdex

on:
  push:
    branches:
      - 'master'

jobs:
     
  apk:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Get NDK 
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;23.0.7196353-beta2"

      - name: Make cross-android
        run: bash ./make.sh cross-android

      - name: Create Release
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: bin

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: bin

